Fix: Download artifacts from the same batch

diff --git a/.github/workflows/CI-compile-video-examples.yml b/.github/workflows/CI-compile-video-examples.yml
--- a/.github/workflows/CI-compile-video-examples.yml
+++ b/.github/workflows/CI-compile-video-examples.yml
@@ -50,8 +50,7 @@ jobs:
           #   examples: "mmf2_video_example_vipnn_handgesture_init mmf2_video_example_joint_test_vipnn_rtsp_mp4_init mmf2_video_example_vipnn_classify_rtsp_init mmf2_video_example_timelapse_mp4_init"
 
     steps:
-      # Checkout the repository into a shorter subdirectory to control
-      # the folder depth and help avoid Windows path length issues
+      # Checkout the repository into a shorter subdirectory to control the folder depth and help avoid Windows path length issues
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
@@ -163,20 +162,28 @@ jobs:
         run: |
           set -x  # Echo each line
           RUN_ID=${{ github.run_id }}
+          BATCH_ID=${{ matrix.batch.id }}
           echo "Run ID: $RUN_ID"
+          echo "Batch ID: $BATCH_ID"
           
-          # Request and save cookie from jenkins server
+          # Request and save cookies and crumb from jenkins server
           curl -c cookies.txt --user "$JENKINS_USER:$JENKINS_TOKEN" "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" > crumb.json
           
+          # Check if file is valid JSON first
+          if ! jq empty crumb.json >/dev/null 2>&1; then
+            echo "ERROR: crumb.json is not valid JSON! Possible server down or bad credentials."
+            exit 1
+          fi
+
           CRUMB=$(jq -r .crumb crumb.json)
           CRUMB_FIELD=$(jq -r .crumbRequestField crumb.json)
 
           echo "CRUMB: $CRUMB"
           echo "CRUMB_FIELD: $CRUMB_FIELD"
           
-          # Trigger job using same cookie
-          # Without -b cookies.txt, jenkins think you are a new client with no session cookie, crumb does not match the session, 403 forbidden
+          # Trigger job using same cookie. Without -b cookies.txt, Jenkins think you are a new client with no session cookie, crumb does not match the session, and results in 403 forbidden
           curl -b cookies.txt -v -X POST "${{ secrets.JENKINS_URL }}/job/test-pipeline-job/buildWithParameters" \
             --user "$JENKINS_USER:$JENKINS_TOKEN" \
             -H "$CRUMB_FIELD: $CRUMB" \
-            --data-urlencode "RUN_ID=$RUN_ID"
+            --data-urlencode "RUN_ID=$RUN_ID" \
+            --data-urlencode "BATCH_ID=$BATCH_ID"
